header:
  scopes:
    grafana:
      # require:
      # - scope: 1
      #   permissions:
      #   - global_admin
      headers:
        X-WEBAUTH-USER: "'provider_attr'.'nameid'"
        # X-WEBAUTH-USER: "'auth_attributes'.'preferred_username'"
        # X-WEBAUTH-NAME: "'auth_attributes'.'name'"
        # X-WEBAUTH-EMAIL: "'auth_attributes'.'email'"

json:
  # endpoint: ""
  scopes:
    galloper:
      login: "'provider_attr'.'nameid'"
      # login: "'auth_attributes'.'preferred_username'"
      # name: "'auth_attributes'.'name'"
      # email: "'auth_attributes'.'email'"
